import Head from "next/head";

import UserInfo from "../component/UserInfo";
import Form from "../component/Form";
import CommentForm from "../component/CommentForm";
import AllComment from "../component/AllComment";
import { AuthContextProvider } from "../store/auth-context";

export default function Home() {
  return (
    <AuthContextProvider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <UserInfo />
        <div
          style={{
            width: "100%",
            height: "30rem",
            display: "flex",
            justifyContent: "space-around",
            backgroundColor: "tan",
          }}
        >
          <Form />
          <CommentForm />
          <AllComment />
        </div>
      </div>
    </AuthContextProvider>
  );
}
